import "@/styles/globals.css";
import { Outfit } from "next/font/google";
import type { AppProps } from "next/app";
import Head from "next/head";
import Navbar from '@/components/Navbar'

const outfit = Outfit({ subsets: ["latin"] });

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Portfolio | Bhat Owais</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.ico" />
      </Head>
      <main className={`${outfit.className} bg-lightBG dark:bg-darkBG`}>
        <Navbar />
        <Component {...pageProps} />
      </main>
    </>
  );
}
